# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 申导
subtitle: Scrum Agile Coach
description: 申健，Jacky Shen, 江湖人称“申导”。创客，工匠，敏捷教练，软件开发顾问。致力于启发创意、促进协作、交付价值的事业。1994年迷上计算机编程，毕业于南京大学。拥有CST认证Scrum培训讲师, CTC认证敏捷教练, CSP，CSM认证和CSPO认证、UCAC认证、看板认证和ToP引导技术认证。Scrum联盟CSD认证课程授权讲师，管理3.0讲师。在跨国企业从事将近十年的研发和管理工作，涉及电信、金融、互联网等领域，拥有丰富的移动应用程序和面向服务分布式系统的项目经验。自2007年开始进入敏捷开发实战，在大型敏捷组织中担任过高级软件工程师、研发经理、ScrumMaster、质量经理、敏捷教练等职位，对大型组织(500人以上)的敏捷转型，团队管理和和工程实践的落地运用具有丰富的经验。《SOA与REST》、《有效的单元测试》、《重塑组织》译者。InfoQ中文站编辑，中国敏捷教练组成员，敏捷之旅、ScrumGathering、QClub等社区活动的组织者及演讲嘉宾。桌游和羽毛球爱好者。
author: Jacky Shen申健
email: jackyshen@uperform.cn
language: zh-cn
timezone: ''
keywords: Scrum认证 创客 工匠 敏捷教练 软件开发顾问 Agile Coaching 申健 申导


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.jackyshen.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:mebusw/mebusw.github.io.git
  branch: gh-pages


sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  rel: false
  tags: true
  categories: true