# Header
menu:
  首页 Main: /
  归档 Archives: /archives
  关于我 About Me: /about-me
  课程 Courses: https://www.uperform.cn/?utm_source=jackyshen
rss: /atom.xml

# Content
excerpt_link: 继续阅读 More
fancybox: true

# Sidebar
sidebar: right
widgets:
- weibo
- recent_posts
- tagcloud
- category
#- tag
- archive

# Miscellaneous
growing_analytics: b95fba2d6958fb5a
cnzz_analytics: 1253167390
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: